version: "3.7"

services:
  frontend:
    build: frontend
    environment:
      - SERVER=https://covid-kb-5b6395f830.wolf.jina.ai
    ports:
      - 8700:8700
    volumes:
      - ./frontend:/workspace
    restart: always
